arping:
  ubuntu: [arping]
  
iperf3:
  ubuntu: [iperf3]

libpqxx-dev:
  ubuntu: [libpqxx-dev]
  
screen:
  ubuntu: [screen]

cimg:
  ubuntu: [cimg-dev]

mpg321:
  ubuntu: [mpg321]

festival:
  ubuntu: [festival]

rtklib:
  ubuntu: [rtklib]

rclone:
  ubuntu: [rclone]

librealsense2:
  ubuntu: [] # install dkms

realsense2_camera:
  ubuntu: [] # build from source

pybind11_catkin:
  ubuntu: [ros-noetic-pybind11-catkin]

rtabmap_ros: # Dervied from ros/rosdistro. Drop rtabmap_examples which installs realsense2 dependencies.
  ubuntu:
    - ros-${ROS_DISTRO}-rtabmap-conversions
    - ros-${ROS_DISTRO}-rtabmap-costmap-plugins
    - ros-${ROS_DISTRO}-rtabmap-demos
    - ros-${ROS_DISTRO}-rtabmap-launch
    - ros-${ROS_DISTRO}-rtabmap-legacy
    - ros-${ROS_DISTRO}-rtabmap-msgs
    - ros-${ROS_DISTRO}-rtabmap-odom
    - ros-${ROS_DISTRO}-rtabmap-python
    - ros-${ROS_DISTRO}-rtabmap-ros
    - ros-${ROS_DISTRO}-rtabmap-rviz-plugins
    - ros-${ROS_DISTRO}-rtabmap-slam
    - ros-${ROS_DISTRO}-rtabmap-sync
    - ros-${ROS_DISTRO}-rtabmap-util
    - ros-${ROS_DISTRO}-rtabmap-viz
