arping:
  ubuntu: [arping]
  
iperf3:
  ubuntu: [iperf3]

libpqxx-dev:
  ubuntu: [libpqxx-dev]
  
screen:
  ubuntu: [screen]

cimg:
  ubuntu: [cimg-dev]

mpg321:
  ubuntu: [mpg321]

festival:
  ubuntu: [festival]

rtklib:
  ubuntu: [rtklib]

rclone:
  ubuntu: [rclone]

librealsense2:
  ubuntu: [] # install dkms

realsense2_camera:
  ubuntu: [] # build from source

pybind11_catkin:
  ubuntu: [ros-noetic-pybind11-catkin]

rtabmap_ros: # Derived from ros/rosdistro. Drop rtabmap_examples which installs realsense2 dependencies.
  ubuntu: [ros-noetic-rtabmap-conversions,
           ros-noetic-rtabmap-costmap-plugins,
           ros-noetic-rtabmap-demos,
           ros-noetic-rtabmap-launch,
           ros-noetic-rtabmap-legacy,
           ros-noetic-rtabmap-msgs,
           ros-noetic-rtabmap-odom,
           ros-noetic-rtabmap-python,
           ros-noetic-rtabmap-ros,
           ros-noetic-rtabmap-rviz-plugins,
           ros-noetic-rtabmap-slam,
           ros-noetic-rtabmap-sync,
           ros-noetic-rtabmap-util,
           ros-noetic-rtabmap-viz]
