arping:
  ubuntu: [arping]
  
iperf3:
  ubuntu: [iperf3]

libpqxx-dev:
  ubuntu: [libpqxx-dev]
  
screen:
  ubuntu: [screen]

cimg:
  ubuntu: [cimg-dev]

mpg321:
  ubuntu: [mpg321]

festival:
  ubuntu: [festival]

rtklib:
  ubuntu: [rtklib]

rclone:
  ubuntu: [rclone]

librealsense2:
  ubuntu: [] # install dkms

realsense2_camera:
  ubuntu: [] # build from source

pybind11_catkin:
  ubuntu: [ros-noetic-pybind11-catkin]
